### ISSUE TITLE
Find and install WordPress theme

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-melissablocations#1]
URL: melissablocations.editllc.com/wp-admin

I already shared the creds with you via lastpass. 

These are some sites that she likes that we should mimic in functionality: 
http://www.arlocations.com
http://www.locationdepartment.net/

**Who is the typical user of your website?**
Photographers looking for locations to do a photoshoot
**What goals do you want to achieve with this project?**
Provide a list of locations information about each location

due:  10-15-15  3p

**Comment by AaronAguilar** [comment]
Hey,

Yesterday you said that you were going to give me more information to put in.

**Comment by rodneystrong** [comment]
ah yes, good job with this. i'll create a new issue for structure/content
