### ISSUE TITLE
menu items

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-melissablocations#4]
- Home page 

- Clients

- Scout

- Search

- Contact

Still not response about content from client. Will keep bugging.

due:
10-17-15  8p

**Comment by rodneystrong** [comment]
just create these pages with filler content for now, and place them into the top header menu

**Comment by AaronAguilar** [comment]
http://melissablocations.editllc.com/ 

there's a search bar on the top left of the menu, so i decided not to include a page for it. The contents have pages on them. Any content to put in?

**Comment by rodneystrong** [comment]
nope, not yet.
