### ISSUE TITLE
remove all branding

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-melissablocations#5]
remove any branding that was on the theme by default: 

<img width="429" alt="screen shot 2015-10-16 at 7 18 45 pm" src="https://cloud.githubusercontent.com/assets/539962/10556555/da4598ac-743a-11e5-8ea1-407807ccdc28.png">

due:
10-17-15  8p

**Comment by AaronAguilar** [comment]
This has already been done. Do you want me to put in other content such as copyright; Melissa B Locations or something else?

**Comment by rodneystrong** [comment]
Yes, please. and then close this once that's done.

**Comment by AaronAguilar** [comment]
Done.
